@echo off
set DEST=.\.exvim.qr_gift_pro
set TOOLS=C:\Users\Anemone\.vim\tools\
set FILE_SUFFIXS=*.PY
set GAWK_SUFFIX=exc
set FILE_FILTER_PATTERN="\\\\.py$"
set FOLDER_FILTER_PATTERN=".*\\\\migrations\\\\.*|.*\\\\static\\\\.*"
set TMP=%DEST%\_files_gawk
set TMP2=%DEST%\_files
set TARGET=%DEST%\files
set ID_TARGET="%DEST%\idutils-files"
call %TOOLS%\shell\batch\update-filelist.bat
