# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonResourceModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('origin_url', models.URLField()),
                ('cdn_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvatarImageModel',
            fields=[
                ('commonresourcemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qr_gift.CommonResourceModel')),
                ('size', models.IntegerField()),
            ],
            bases=('qr_gift.commonresourcemodel',),
        ),
    ]
