# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0003_usermodel_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='nick',
            field=models.CharField(default='\u8def\u4eba\u7532', max_length=256),
        ),
    ]
