# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 12:55
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0004_auto_20160222_1007'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='qrstylemodel',
            name='style_binary',
        ),
        migrations.AddField(
            model_name='qrstylemodel',
            name='style_border_binary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_border_res', to='qr_gift.CommonResourceModel'),
        ),
        migrations.AddField(
            model_name='qrstylemodel',
            name='style_center_binary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_center_res', to='qr_gift.CommonResourceModel'),
        ),
        migrations.AddField(
            model_name='qrstylemodel',
            name='style_script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_script_res', to='qr_gift.CommonResourceModel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qr_gift.CommonResourceModel'),
        ),
        migrations.AlterField(
            model_name='qrcodemodel',
            name='card_token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qr_gift.CardModel'),
        ),
        migrations.AlterField(
            model_name='qrstylemodel',
            name='preview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview_res', to='qr_gift.CommonResourceModel'),
        ),
    ]
