# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0006_auto_20160222_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonresourcemodel',
            name='cdn_url',
            field=models.URLField(null=True),
        ),
    ]
