# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0009_auto_20160222_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonresourcemodel',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
