# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0010_auto_20160222_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodemodel',
            name='card_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='qr_gift.CardModel'),
        ),
        migrations.AlterField(
            model_name='qrcodemodel',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrcodemodel',
            name='is_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qrcodemodel',
            name='recorded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='qrcodemodel',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qrstylemodel',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrstylemodel',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
