# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0011_auto_20160223_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='logo',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='birthday',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='constellation',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='province',
            field=models.CharField(default='', max_length=32),
        ),
    ]
