# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0013_auto_20160226_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonresourcemodel',
            name='cdn_url',
        ),
        migrations.RemoveField(
            model_name='commonresourcemodel',
            name='origin_url',
        ),
        migrations.AddField(
            model_name='commonresourcemodel',
            name='id_md5',
            field=models.CharField(default='', max_length=32),
        ),
    ]
