# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0017_auto_20160227_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonresourcemodel',
            name='sha_256',
            field=models.CharField(default='', max_length=256),
        ),
    ]
