# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0018_commonresourcemodel_sha_256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonresourcemodel',
            name='sha_256',
            field=models.CharField(default='', max_length=64),
        ),
    ]
