# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0019_auto_20160328_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaliyNewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(max_length=16)),
                ('string', models.CharField(max_length=1024)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_res', to='qr_gift.CommonResourceModel')),
            ],
        ),
        migrations.CreateModel(
            name='DaliyNewsStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='daliynewsmodel',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_gift.DaliyNewsStyleModel'),
        ),
        migrations.AddField(
            model_name='daliynewsmodel',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_res', to='qr_gift.CommonResourceModel'),
        ),
        migrations.AddField(
            model_name='daliynewsmodel',
            name='voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_res', to='qr_gift.CommonResourceModel'),
        ),
    ]
