# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0020_auto_20160328_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daliynewsmodel',
            name='string',
            field=models.TextField(),
        ),
    ]
