# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0021_auto_20160328_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daliynewsmodel',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_res', to='qr_gift.CommonResourceModel'),
        ),
    ]
