# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0023_auto_20160329_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='qr_gift.CommonResourceModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avater', to='qr_gift.CommonResourceModel'),
        ),
    ]
