# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gift', '0024_auto_20160402_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daliynewsmodel',
            old_name='voice',
            new_name='audio',
        ),
    ]
